language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
  - "nightly"
# command to install dependencies
install:
  - pip install requests
  - pip install python-coveralls
  - pip install coverage
# command to run tests
script:
  - nosetests -v --with-coverage --cover-tests --cover-package=grafana_api test/test_grafana.py
after_success:
  - coveralls
